apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go-deployment
spec:
  selector:
    matchLabels:
      app: gobackend
  template:
    metadata:
      labels:
        app: gobackend
    spec:
      containers:
      - name: gobackend
        image: database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
