apiVersion: v1
kind: PersistentVolume            
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard      
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                      
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain 
