apiVersion: v1
kind: Service
metadata:
  name: reactfrontend
spec:
  selector:
    app: reactfrontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
status: 
  loadBalancer: {}

