
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  workspaces:
    - name: source
  steps:
    - name: db-deployment
      image:  lachlanevenson/k8s-kubectl
      workingdir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args: ["-c"," kubectl apply -f ./K8s/dbDeployment.yaml; kubectl apply -f ./K8s/dbService.yaml"]
    - name: go-deployment
      image:  lachlanevenson/k8s-kubectl
      workingdir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args: ["-c"," kubectl apply -f ./K8s/goDeployment.yaml; kubectl apply -f ./K8s/goService.yaml"]
    - name: react-deployment
      image:  lachlanevenson/k8s-kubectl
      workingdir: $(workspaces.source.path)
      command: ["/bin/sh"]
      args: ["-c"," kubectl apply -f ./K8s/reactDeployment.yaml; kubectl apply -f ./K8s/reactService.yaml"]
