version: '3'
services:
  mysqldb:
    container_name: mysqldb
    networks: 
      - servernetwork
    image: mysql:5.7
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=mysqldb
      - MYSQL_USER=khyati
      - MYSQL_PASSWORD=khyati
      - MYSQL_DATABASE=goServer
      - MYSQL_ROOT_PASSWORD=sup3rPw#
    volumes:
      - database_mysql:/var/lib/mysql
  frontend:
    container_name: reactjsfrontend
    image: reactserver:v1
    networks: 
      - servernetwork
    environment:
      PROXY_API: http://backend:9000/
    ports:
      - 8000:8000
  backend:
    container_name: gobackend
    networks: 
      - servernetwork
    image: database:v1
    depends_on:
      - "mysqldb"
    ports:
      - 9000:9000
networks: 
  servernetwork: {}
volumes:
  database_mysql: 


