apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: mysql-pv-claim
  labels:
    app: mysqldb
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce                
  resources:
    requests:
      storage: 250Mi
